name: Release manual

on: 
  push:              # workflow initially not visible in Actions
  workflow_dispatch: # Triggered manually for Release

jobs:
  maven_release:
    runs-on: ubuntu-latest
    name: Release with Maven

    steps: 
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v3

    # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven
    - name: Set up Environment
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.RISECLIPSE_PGP_KEY_PRIVATE }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Configure Git User
      run: |
        git config user.email github-actions@github.com
        git config user.name "GitHub Actions"

    - name: Switch branch to do Release
      run: |
        git branch do_release
        git switch do_release
        git push --set-upstream origin do_release 

    - name: Prepare Maven Release
      run: |
        mvn --batch-mode release:prepare    

    - name: Perform Maven Release and Publish to OSSRH/Apache Maven Central
      run: mvn --batch-mode release:perform
      env:
        MAVEN_USERNAME: ${{ secrets.RISECLIPSE_OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.RISECLIPSE_OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.RISECLIPSE_PGP_KEY_PASSWORD }}

    - name: Clean before creating PR and push tag
      run: |
        mvn clean
        git push --tags

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        base: master
        branch: do_release
        labels: automated pr
        title: '[maven-release-plugin] prepare for next development iteration after release'

